#!/usr/bin/python
#Filename = multilinestring.py
print('''This is a multi-line string.  This is the first line.\n
This is the second line.
"What's your name?," I asked.
He said "Bond, James Bond.''')
